# Generated by Django 5.1.6 on 2025-02-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LIBRARIAN', 'Librarian'), ('MEMBER', 'Member')], default='MEMBER', max_length=100),
        ),
    ]
